spring:
  application:
    name: eureka-server

server:
  port: 8762

target:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${target.port}/eureka/