spring:
  application:
    name: eureka-server

server:
  port: 8762

target:
  port: 8763

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${target.port}/eureka/