spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/mayun_manong/springcloud
          username: tk1143413@163.com
          password: mayun_manong
          basedir: /home/shisj/tmp/config-git/
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

target:
  port: 8761

server:
  port: 9090

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${target.port}/eureka/

management:
  endpoints:
    web:
      exposure:
        include: bus-refresh