spring:
  application:
    name: order
  datasource:
    url: jdbc:mysql://localhost:3306/dinner?characterEncoding=utf8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true
      stat-view-servlet.allow: true
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.shisj.study.dinner.order.dataobject

server:
  port: 8081

# 设置eureka的地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/