spring:
  application:
    name: zuulproduct
  zipkin:
    base-url: http://localhost:9411/
  sleuth:
    sampler:
      percentage: 1

server:
  port: 9999

eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/